export interface SearchLink {
  term: string;
  count: string;
}

export interface SearchCategory {
  label: string;
  links: SearchLink[];
}

export const POPULAR_SEARCHES: SearchCategory[] = [
  {
    label: 'RV type',
    links: [
      { term: 'Class A motorhomes for sale', count: '12,345' },
      { term: 'Class B camper vans for sale', count: '8,901' },
      { term: 'Class C motorhomes for sale', count: '15,678' },
      { term: 'Travel trailers for sale', count: '46,098' },
      { term: 'Fifth wheel RVs for sale', count: '22,456' },
      { term: 'Pop up campers for sale', count: '5,432' },
      { term: 'Toy haulers for sale', count: '9,876' },
      { term: 'Truck campers for sale', count: '3,210' },
      { term: 'Park model RVs for sale', count: '2,145' },
      { term: 'Diesel pushers for sale', count: '4,567' },
      { term: 'Hybrid trailers for sale', count: '1,890' },
      { term: 'Teardrop trailers for sale', count: '3,456' },
      { term: 'Expandable trailers for sale', count: '1,234' },
      { term: 'Fish house trailers for sale', count: '987' },
      { term: 'Sport utility trailers for sale', count: '2,678' },
      { term: 'Converted bus RVs for sale', count: '1,543' },
      { term: 'Micro minnie trailers for sale', count: '4,321' },
      { term: 'Off-road travel trailers for sale', count: '2,109' },
    ],
  },
  {
    label: 'Travel trailers',
    links: [
      { term: 'Travel trailers under $10,000', count: '3,456' },
      { term: 'Travel trailers under $20,000', count: '8,901' },
      { term: 'Travel trailers under $30,000', count: '14,567' },
      { term: 'Travel trailers near me', count: '8,901' },
      { term: 'Used travel trailers for sale', count: '32,145' },
      { term: 'New travel trailers for sale', count: '13,953' },
      { term: 'Lightweight travel trailers', count: '6,789' },
      { term: 'Travel trailers with bunk beds', count: '5,432' },
      { term: 'Small travel trailers for sale', count: '7,654' },
      { term: 'Travel trailers with slide outs', count: '11,234' },
      { term: 'Keystone travel trailers for sale', count: '9,876' },
      { term: 'Forest River travel trailers', count: '12,345' },
      { term: 'Jayco travel trailers for sale', count: '8,765' },
      { term: 'Coachmen travel trailers for sale', count: '6,543' },
      { term: 'Winnebago travel trailers for sale', count: '4,321' },
      { term: 'Grand Design travel trailers', count: '7,890' },
      { term: 'Airstream travel trailers for sale', count: '3,210' },
      { term: 'Heartland travel trailers for sale', count: '5,678' },
    ],
  },
  {
    label: 'Fifth wheels',
    links: [
      { term: 'Fifth wheels under $30,000', count: '4,567' },
      { term: 'Fifth wheels under $50,000', count: '9,012' },
      { term: 'Fifth wheels near me', count: '6,789' },
      { term: 'Used fifth wheels for sale', count: '18,234' },
      { term: 'New fifth wheels for sale', count: '4,208' },
      { term: 'Luxury fifth wheels for sale', count: '3,456' },
      { term: 'Fifth wheels with 2 bedrooms', count: '2,345' },
      { term: 'Fifth wheels with washer dryer', count: '4,567' },
      { term: 'Keystone fifth wheels for sale', count: '5,678' },
      { term: 'Forest River fifth wheels', count: '7,890' },
      { term: 'Grand Design fifth wheels', count: '6,543' },
      { term: 'Heartland fifth wheels for sale', count: '4,321' },
      { term: 'Montana fifth wheels for sale', count: '3,210' },
      { term: 'Alliance fifth wheels for sale', count: '2,109' },
      { term: 'Jayco fifth wheels for sale', count: '3,456' },
      { term: 'Coachmen fifth wheels for sale', count: '2,345' },
      { term: 'Palomino fifth wheels for sale', count: '1,890' },
      { term: 'Highland Ridge fifth wheels', count: '2,678' },
    ],
  },
  {
    label: 'Class A',
    links: [
      { term: 'Class A RVs under $50,000', count: '3,456' },
      { term: 'Class A RVs under $100,000', count: '7,890' },
      { term: 'Class A diesel pushers for sale', count: '4,567' },
      { term: 'Used Class A motorhomes', count: '10,234' },
      { term: 'New Class A motorhomes for sale', count: '2,098' },
      { term: 'Class A RVs near me', count: '5,432' },
      { term: 'Small Class A motorhomes', count: '2,345' },
      { term: 'Class A motorhomes with bunk beds', count: '1,890' },
      { term: 'Tiffin Class A motorhomes', count: '3,210' },
      { term: 'Thor Class A motorhomes for sale', count: '4,567' },
      { term: 'Winnebago Class A motorhomes', count: '3,456' },
      { term: 'Newmar Class A motorhomes', count: '2,345' },
      { term: 'Coachmen Class A motorhomes', count: '2,109' },
      { term: 'Fleetwood Class A for sale', count: '3,678' },
      { term: 'Entegra Class A motorhomes', count: '1,543' },
      { term: 'Forest River Class A for sale', count: '2,890' },
      { term: 'Holiday Rambler Class A for sale', count: '1,234' },
      { term: 'Luxury Class A motorhomes', count: '2,567' },
    ],
  },
  {
    label: 'Class C',
    links: [
      { term: 'Class C RVs under $50,000', count: '5,678' },
      { term: 'Class C RVs under $100,000', count: '10,234' },
      { term: 'Used Class C motorhomes', count: '12,345' },
      { term: 'New Class C motorhomes for sale', count: '3,321' },
      { term: 'Class C RVs near me', count: '7,654' },
      { term: 'Small Class C motorhomes', count: '4,321' },
      { term: 'Class C motorhomes with bunk beds', count: '3,456' },
      { term: 'Super C motorhomes for sale', count: '2,109' },
      { term: 'Thor Class C motorhomes for sale', count: '5,432' },
      { term: 'Winnebago Class C motorhomes', count: '4,567' },
      { term: 'Jayco Class C motorhomes', count: '3,210' },
      { term: 'Coachmen Class C motorhomes', count: '3,890' },
      { term: 'Forest River Class C for sale', count: '4,321' },
      { term: 'Dynamax Class C motorhomes', count: '1,234' },
      { term: 'Entegra Class C for sale', count: '987' },
      { term: 'Nexus Class C motorhomes', count: '1,543' },
      { term: 'Class C diesel motorhomes', count: '2,345' },
      { term: 'Mercedes Class C motorhomes', count: '1,890' },
    ],
  },
];
